
language: android

jdk: oraclejdk8

android:
  components:
     - tools
     - platform-tools

    # The BuildTools version 
     - build-tools-25.0.2
     - extra-android-m2repository
     - extra-google-android-support
     - yes | sdkmanager "platforms;android-27"

    # The SDK version used to compile your project
     - android-16
     - android-21
     - android-22
     - android-25

    # Run emulator(s) during your tests
     - sys-img-armeabi-v7a-android-16
     - sys-img-armeabi-v7a-android-21
     - sys-img-armeabi-v7a-android-22
     - sys-img-armeabi-v7a-android-25

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    


script: ./gradlew assembleDebug
